matches:
  - trigger: ";today"
    replace: "{{data}}"
    vars:
      - name: data
        type: date
        params:
          format: "%d/%m/%Y"

  - trigger: ";now"
    replace: "{{hora}}"
    vars:
      - name: hora
        type: date
        params:
          format: "%d/%m/%Y %H:%M"

  - trigger: ";email"
    replace: "joaomarceloav@gmail.com"

  - trigger: ";cpf"
    replace: "99751429315"

  - trigger: ";nome"
    replace: "João Marcelo Araújo Vieira"

  - trigger: ";ass"
    replace: |
      Atenciosamente,
      João Marcelo Araújo Vieira
      Auditor Fiscal de Tributos Municipais — SMFA/BH

  - trigger: ";flacpf"
    replace: "99223627320"

  - trigger: ";flacnpj"
    replace: "62233012000113"
