-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL P2217H HJPT578B2L3B",
  mode = "1920x1080@60.00",
  position = "3840x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Lenovo Group Limited T22i-30 VAC52708",
  mode = "1920x1080@60.00",
  position = "1920x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "name:DP-1:1", monitor = "desc:Lenovo Group Limited T22i-30 VAC52708", persistent = true })
hl.workspace_rule({ workspace = "name:DP-1:2", monitor = "desc:Lenovo Group Limited T22i-30 VAC52708", persistent = true })
hl.workspace_rule({ workspace = "name:DP-1:3", monitor = "desc:Lenovo Group Limited T22i-30 VAC52708", persistent = true })
hl.workspace_rule({ workspace = "name:DP-1:4", monitor = "desc:Lenovo Group Limited T22i-30 VAC52708", persistent = true })
hl.workspace_rule({ workspace = "name:DP-1:5", monitor = "desc:Lenovo Group Limited T22i-30 VAC52708", persistent = true })
hl.workspace_rule({ workspace = "name:HDMI-A-1:1", monitor = "desc:Dell Inc. DELL P2217H HJPT578B2L3B", persistent = true })
hl.workspace_rule({ workspace = "name:HDMI-A-1:2", monitor = "desc:Dell Inc. DELL P2217H HJPT578B2L3B", persistent = true })
hl.workspace_rule({ workspace = "name:HDMI-A-1:3", monitor = "desc:Dell Inc. DELL P2217H HJPT578B2L3B", persistent = true })
hl.workspace_rule({ workspace = "name:HDMI-A-1:4", monitor = "desc:Dell Inc. DELL P2217H HJPT578B2L3B", persistent = true })
hl.workspace_rule({ workspace = "name:HDMI-A-1:5", monitor = "desc:Dell Inc. DELL P2217H HJPT578B2L3B", persistent = true })
